apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla
data:
  cassandra-rackdc.properties: |
    dc = us-west-2
    prefer-local = false
  #scylla.yaml: 'enable_keyspace_column_family_metrics: true'
  scylla.yaml: |
    api_address: 127.0.0.1
    api_doc_dir: /opt/scylladb/api/api-doc/
    api_port: 10000
    api_ui_dir: /opt/scylladb/swagger-ui/dist/
    batch_size_fail_threshold_in_kb: 1024
    batch_size_warn_threshold_in_kb: 128
    cas_contention_timeout_in_ms: 1000
    cluster_name: {{ include "scylla.fullname" .}}
    commitlog_segment_size_in_mb: 32
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_total_space_in_mb: -1
    enable_keyspace_column_family_metrics: true
    endpoint_snitch: GossipingPropertyFileSnitch
    force_schema_commit_log: true
    listen_address: localhost
    murmur3_partitioner_ignore_msb_bits: 12
    native_shard_aware_transport_port: 19042
    native_transport_port: 9042
    num_tokens: 256
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    read_request_timeout_in_ms: 5000
    rpc_address: 0.0.0.0
    rpc_port: 9160
    seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
      - seeds: 127.0.0.1
    write_request_timeout_in_ms: 2000
  entrypoint.sh: |
    #!/bin/bash

    # Determine region and zone
    TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
    AZ=`curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/placement/availability-zone`
    RACK=`echo $AZ | awk -F'-' '{print $3}'`

    echo "REGION: ${AWS_REGION}"
    echo "ZONE: ${AZ}"
    echo "RACK: ${RACK}"
    cat > /etc/scylla/cassandra-rackdc.properties <<- EOF
    dc = ${AWS_REGION} 
    rack = ${RACK}
    prefer_local = false
    EOF

    echo ------C* RACK PROPS-------
    cat /etc/scylla/cassandra-rackdc.properties
    echo --------------------------

    cp /mnt/scylla-config/scylla.yaml /etc/scylla/scylla.yaml
    if grep -q "scylla/replace-address" /etc/podinfo/labels; then
      REPLACE_ADDRESS=`grep -oP 'scylla\/replace-address="(\K[\d\.]+)' /etc/podinfo/labels`
      echo REPLACE_ADDRESS: ${REPLACE_ADDRESS}
      echo "replace_address_first_boot: ${REPLACE_ADDRESS}" >> /etc/scylla/scylla.yaml
    fi

    echo "Runnning docker-entrypoint.py $@"
    /docker-entrypoint.py "$@"
  ready-probe.sh: |
    #!/bin/bash

    if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
      if [[ $DEBUG ]]; then
        echo "UN";
      fi
      exit 0;
    else
      if [[ $DEBUG ]]; then
        echo "Not Up";
      fi
      exit 1;
    fi