apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "scylla.labels" . | nindent 4 }}
  name: scylla-auth-token
data:
  auth-token.yaml: {{ (printf "auth_token: %s\n" .Values.scyllaManager.token) | b64enc }}
type: Opaque