apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "scylla.labels" . | nindent 4 }}
  name: scylla-agent-config
type: Opaque
stringData: 
  scylla-manager-agent.yaml: |-
    s3:
      region: us-west-2